blockers:
  schematica-printer: true
  schematica-load: true
  schematica-save: true

database:
  use-database: false
  username: root
  password: password
  database: ModDetector
  host: localhost
  port: 3306